### ISSUE TITLE
[Feature Request] Resize

### ISSUE THREAD

**Issue by WeylonSantana** [OniSensei/Intersect-GUI-Editor#4]
![image](https://user-images.githubusercontent.com/63019821/116955044-dcbe4c80-ac67-11eb-984e-2992eddcdbda.png)

When a property in the gui has a "texture", changing the width/heigth in the bounds deforms the image designated in the texture as well, resizes the image, it would be nice to have that in here as well.

**Comment by OniSensei** [comment]
This would normally happen, however if you look, the texture is actually appointed to the `EntityInfoPanel` so resizing the `PlayerBox` bounds will not effect this texture.

Reference:
https://github.com/OniSensei/Intersect-GUI-Editor/issues/7#issuecomment-832274168

The property is set to stretch the image to the size of the panel, if the image is lets say 16x16px, and the panel is 200x300, the quality of the image is going to be terrible due to stretching it over 200-300 pixels.
